
project_id = "ghucegvhempgmdykosiw"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = false

[functions.admin-recent-activity]
verify_jwt = true
